# This is a basic workflow to help you get started with Actions

name: Test

on:
  workflow_dispatch:
    inputs:
      action-name:
        type: string


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ${{ github.event.inputs.action-name }}
